services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/nodedb
      - APP_NAME=Share Your Idea
      - JWT_SECRET=sadq43jhoy!5udh2qdsw#ln6d%as18ñ43siau&d9y/12)e
      - CACHE_KEY=MyStr0ngP&ssw@rd!
      - SWAGGER_DOC=swaggerPROD
    ports:
      - "5000:5000"
  mongo:
    image: mongo
